pubspec.yaml

Bumped app version to 0.17.0

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/internet_settings/views/internet_settings_mac_clone_view.dart

Fixed clone current's MAC not working;
Update MAC input field as Outline style

Fixed clone current's MAC not working; Update MAC input field as Outline style

---

lib/core/http/linksys_http_client.dart
lib/core/jnap/command/http/jnap_retry_options.dart
lib/core/jnap/jnap_command_executor_mixin.dart
lib/core/jnap/providers/side_effect_provider.dart
lib/core/jnap/router_repository.dart
lib/page/nodes/views/add_nodes_view.dart
lib/page/pnp/data/pnp_provider.dart
lib/page/pnp/model/impl/your_network_step.dart
lib/page/pnp/model/pnp_step.dart

* Add retries and timeout attrs for RouterRepository.send() and .transaction(); 
* Update PnP config UI

Add retries and timeout attrs 

---

lib/core/jnap/models/wan_settings.dart
lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart

1. Fix state not updated after save setting on changed connection type
2. Modify the save setting functions
3. Update the widgets.diff file

Update advanced settings

---

lib/l10n/app_en.arb
lib/page/administration/firewall/providers/ipv6_port_service_list_provider.dart
lib/page/administration/firewall/providers/ipv6_port_service_rule_provider.dart
lib/page/administration/firewall/views/ipv6_port_service_list_view.dart
lib/page/administration/firewall/views/ipv6_port_service_rule_view.dart
lib/page/administration/network_admin/views/network_admin_view.dart
lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/health_check/views/speed_test_selection.dart
lib/page/wifi_settings/views/wifi_list_view.dart
lib/page/wifi_settings/views/wifi_share_tab_view.dart

- Fixed WiFi list doesn't update state after changes
- Fixed Ipv6 port service add/delete rules not working
- Update router password and hint UX
- Fixed internet to device speed check always disabled
- Fixed WiFi share view doesn't include guest WiFi

Minor issues fixing

---

test/page/dashboard/views/dashboard_menu_view_test.dart

Update testcase because remove an item on the UI

Update testcase because remove an item on the UI

---

lib/page/pnp/pnp_admin_view.dart

save admin password after fetch device info and go to pnp setup view after check admin password passed

save admin password after fetch device info and go to pnp setup view after check admin password passed

---

lib/core/jnap/providers/side_effect_provider.dart
lib/core/utils/devices.dart
lib/page/components/layouts/root_container.dart
lib/page/components/shortcuts/spinners.dart
lib/page/components/styled/general_settings_widget/general_settings_widget.dart
lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/topology/providers/topology_provider.dart

Add show full screen spinner overlay function on shortcuts.
Add JNAP side effect error to handle unsuccess side effect case.
Update spinner when restarting router
Update dialog when confirm to restart router

Add show full screen spinner overlay function on shortcuts.

---

lib/page/dashboard/views/_views.dart
lib/page/dashboard/views/dashboard_support_view.dart
lib/page/pnp/troubleshooter/views/contact_support/contact_support_selection_view.dart
lib/page/support/callback_description_view.dart
lib/page/support/faq_list_view.dart
lib/route/constants.dart
lib/route/route_dashboard.dart
lib/route/route_pnp.dart
lib/route/router_provider.dart
test/page/dashboard/views/dashboard_shell_test.dart

1. Implemented the Dashboard Support feature including several pages
2. Rename the "DashboardSupport" view to "CallbackDescription" view

[Dashboard Support]

---

lib/l10n/app_en.arb
lib/page/login/views/local_router_recovery_view.dart

Removed the 'Show me where' button and the string

[Forget Password]

---

lib/page/pnp/model/impl/night_mode_step.dart
lib/page/support/views/callback_request_view.dart

1. Fix region button disable on callback request page
2. Set night mode default to false

[Fix] Bug fix

---

lib/page/administration/dmz/views/dmz_settings_view.dart
lib/page/administration/firewall/views/ipv6_port_service_rule_view.dart

[DMZ] Fix can not go back issue

---

build_web.sh
lib/page/pnp/data/pnp_provider.dart
pubspec.yaml

- Remove source map generation process
- Fixed throw wrong exception when side effect timeout

- Bump version to 0.17.1

---

lib/page/health_check/providers/health_check_provider.dart
lib/page/health_check/views/speed_test_view.dart

Add background for speed test on running and complete views. Modify the animation frequency for smoothness.

[Speed Test] Add background for speed test on running and complete views. Modify the animation frequency for smoothness.

---

run_generate_loc_snapshots.sh
test/common/config.dart
test/common/test_responsive_widget.dart

- Fixed some locales can't be executed
- Generate html testing report with localses and screens naming.

Fixed some locales can't be executed

---

lib/l10n/app_en.arb
lib/page/nodes/providers/add_nodes_provider.dart
lib/page/nodes/providers/add_nodes_state.dart
lib/page/nodes/views/add_nodes_view.dart

Add refresh function on add node result view

[Add Node] Add refresh function on add node result view

---

lib/page/firmware_update/views/firmware_update_detail_view.dart
test/page/firmware_update/views/localizations/firmware_update_detail_view_test.dart
test/test_data/firmware_update_test_state.dart

1. Added screenshot testing for firmware update
2. Fixed spinner UI bugs in updating view

[Screenshot Testing]

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/internet_settings/views/connection_type_view.dart
lib/page/advanced_settings/internet_settings/views/internet_settings_mac_clone_view.dart
lib/page/components/shortcuts/dialogs.dart
test/page/advanced_settings/internet_settings/views/localizations/connection_type_selection_view_test.dart
test/page/advanced_settings/internet_settings/views/localizations/connection_type_view_test.dart
test/page/advanced_settings/internet_settings/views/localizations/internet_settings_mac_clone_view_test.dart
test/page/advanced_settings/internet_settings/views/localizations/internet_settings_view_test.dart
test/page/dashboard/localizations/dashboard_advanced_settings_view_test.dart
test/test_data/internet_settings_state_data.dart

Localization testing for ineternet settings. Fix issue on subnet mask input in internet settings.

[Testing] Localization testing for ineternet settings. Fix issue on subnet mask input in internet settings.

---

lib/constants/error_code.dart
lib/l10n/app_en.arb
lib/page/advanced_settings/static_routing/static_routing_detail_view.dart
lib/page/login/views/local_router_recovery_view.dart
lib/page/network_admin/providers/router_password_provider.dart
lib/utils.dart

[APPS-339] [Forgot Password] Missing the error message of locked out on forgot password
[APPS-343] [Advanced Routing] Add static routing does not have any responses if users input an invalid subnet mask
[APPS-344] [Advanced Routing] Unknown error is prompted if users input an invalid gateway
[APPS-345] [Advanced Routing] Failed static routing settings will appear on the static routing table

Fixed the issues and added error handling in ResetPassword and Advanced Routing

---

lib/l10n/app_en.arb
lib/page/advanced_settings/port_forwarding/providers/port_range_forwarding_rule_provider.dart
lib/page/advanced_settings/port_forwarding/providers/port_range_triggering_rule_provider.dart
lib/page/advanced_settings/port_forwarding/providers/port_util_mixin.dart
lib/page/advanced_settings/port_forwarding/providers/single_port_forwarding_rule_provider.dart
lib/page/advanced_settings/port_forwarding/views/port_range_forwarding_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/port_range_triggering_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/single_port_forwarding_rule_view.dart
lib/utils.dart

- Fixed no error message for checking ip field on single port forwarding page and port range forwarding page
- Fixed no error message for check port range is valid
- Fixed no error message for port overlap
- Add error snackbar when save/delete error

Fixed port settings issues

---

lib/l10n/app_en.arb
lib/page/components/shortcuts/dialogs.dart
lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/support/faq_list_view.dart
lib/route/route_dashboard.dart

- Fixed forcing logout when restarting router
- Navigate support page to faq list

Fixed forcing logout when restarting router

---

lib/main.dart
lib/page/advanced_settings/port_forwarding/providers/port_range_forwarding_rule_provider.dart
lib/page/advanced_settings/port_forwarding/providers/port_range_triggering_rule_provider.dart
lib/page/advanced_settings/port_forwarding/views/port_range_forwarding_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/port_range_triggering_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/single_port_forwarding_rule_view.dart

Fix add/delete rules state sync issue.

[Port Setting] Fix add/delete rules state sync issue.

---

lib/page/devices/views/device_detail_view.dart
lib/page/network_admin/providers/timezone_provider.dart
lib/page/nodes/views/node_detail_view.dart

- fixed device/node details display signal strength if is wired connection
- sorting orders by timezone value in timezone selection page

-fixed device/node details display signal strength if is wired connection

---

lib/page/components/shortcuts/dialogs.dart
lib/page/components/styled/styled_page_view.dart
lib/page/support/faq_list_view.dart
pubspec.yaml
web/index.html

- Fixed faq links
- Restore go_router version

Fixed faq links

---

lib/page/components/styled/general_settings_widget/general_settings_widget.dart
lib/page/components/styled/general_settings_widget/language_tile.dart
lib/page/components/styled/styled_page_view.dart
lib/page/dashboard/views/components/wifi_grid.dart
lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/login/views/login_local_view.dart
lib/page/support/faq_list_view.dart
lib/page/topology/views/topology_view.dart
pubspec.yaml

download grade to 3.19.2 and it dependencies

download grade to 3.19.2 and it dependencies

---

lib/constants/url_links.dart
lib/page/components/styled/bottom_bar.dart
lib/page/components/styled/general_settings_widget/general_settings_widget.dart
lib/page/support/faq_list_view.dart

- Add goToOffcialWebPage with locale
- Clean up KB articles

- Add goToOffcialWebPage with locale

---

lib/constants/url_links.dart

- Fixed wrong url combination with locale

- Fixed wrong url combination with locale

---

lib/constants/url_links.dart

- Fixed URL case-sensitive issue

- Fixed url case sensitive issue

---

lib/core/jnap/providers/polling_provider.dart
lib/core/jnap/router_repository.dart
lib/core/utils/logger.dart
lib/page/components/styled/general_settings_widget/general_settings_widget.dart
lib/page/login/views/login_local_view.dart
lib/page/pnp/pnp_admin_view.dart
lib/page/select_network/views/select_network_view.dart
lib/page/troubleshooting/views/troubleshooting_view.dart
lib/providers/auth/auth_provider.dart

1. Added more logs in the authentication process of the app
2. Added a new section for LinksysCache in the log output file

[Clean Logs]

---

lib/core/jnap/providers/device_manager_provider.dart
lib/core/utils/devices.dart
lib/page/dashboard/providers/dashboard_home_provider.dart
lib/page/instant_device/providers/device_list_provider.dart
lib/page/instant_safety/providers/safe_browsing_provider.dart
lib/page/instant_topology/providers/topology_provider.dart
lib/page/nodes/providers/add_nodes_provider.dart
lib/page/nodes/providers/node_detail_provider.dart
lib/page/nodes/views/connected_device_widget.dart
lib/page/troubleshooting/providers/troubleshooting_provider.dart
lib/page/wifi_settings/providers/channelfinder_provider.dart
lib/page/wifi_settings/providers/guest_wifi_provider.dart
lib/page/wifi_settings/providers/wifi_list_provider.dart

- Update device isOnline
- Add device getConnectionType
- Remove device isWirelessConnection

- Update device isOnline

---

lib/page/dashboard/views/components/networks.dart
lib/page/dashboard/views/components/privacy.dart

- update instant privacy tile
- update uptime format

- update instant privacy tile

---

lib/page/advanced_settings/administration/views/administration_settings_view.dart
lib/page/instant_device/views/device_detail_view.dart
lib/route/route_menu.dart

1. Add semantic label for back button, close button, switch and checkbox
2. Fix select device page issue

[Semantic Label] 1. Add semantic label for back button, close button, switch and checkbox

---

lib/l10n/app_en.arb
lib/page/instant_device/views/device_detail_view.dart
lib/page/instant_device/views/instant_device_view.dart
lib/page/nodes/views/node_detail_view.dart

[Instant Device] Instant device re-work

---

lib/core/cache/linksys_cache_manager.dart
lib/core/cloud/linksys_device_cloud_service.dart
lib/core/cloud/providers/geolocation/geolocation_provider.dart
lib/core/http/linksys_http_client.dart

- Refactor data parsing for geolocation
- Add cache mechanism for geolocation cloud API

- Refactor data parsing for geolocation

---

lib/core/jnap/actions/better_action.dart
lib/core/jnap/actions/jnap_action.dart
lib/core/jnap/actions/jnap_action_value.dart
lib/core/jnap/actions/jnap_service.dart
lib/core/jnap/actions/jnap_service_supported.dart
lib/core/jnap/providers/dashboard_manager_provider.dart
lib/core/jnap/providers/dashboard_manager_state.dart
lib/l10n/app_en.arb
lib/page/instant_verify/views/instant_verify_view.dart

- Add new JNAP services
- Add new JNAP actions
- integrate cpu and memory load

JNAPs integratation

---

lib/core/jnap/providers/device_manager_provider.dart
lib/l10n/app_en.arb
lib/page/instant_device/views/device_list_widget.dart
lib/page/instant_device/views/instant_device_view.dart
lib/page/nodes/views/node_detail_view.dart

Add disconnect client function to device page and node detail page

[Deauth] Add disconnect client function to device page and node detail page

---

lib/core/http/linksys_http_client.dart

- Fixed unexcepted error when parsing response

Hotfix parsing issue

---

lib/core/jnap/providers/side_effect_provider.dart
lib/page/components/shortcuts/dialogs.dart
lib/page/instant_safety/providers/instant_safety_provider.dart
lib/page/instant_safety/views/instant_safety_view.dart

- auto stop polling when starting handling side effect
- fixed not showing router not found when router is disconnected

NOW-152: Instant-Safety: Blank page appears when updating safe browsing settings

---

lib/page/instant_safety/views/instant_safety_view.dart

Add unsaved alert for state change.

[NOW-153] Instant-Safety: It does not prompt the user that there are unsaved changes on the page

---

lib/core/jnap/providers/dashboard_manager_provider.dart
lib/l10n/app_en.arb
lib/page/components/shortcuts/dialogs.dart
lib/page/wifi_settings/providers/wifi_list_provider.dart
lib/page/wifi_settings/views/wifi_list_view.dart

- [NOW-163]: Incredible-WiFi: Error message displays when turning on the WiFi band
- [NOW-164]: Guest WiFi should be broadcast after turning on the main WiFi band
- [NOW-166]: Incredible-WiFi: It is recommended to display a message informing the user that disabling the main WiFi band will also disable guest WiFi band access
- [NOW-167]: Incredible-WiFi: Error message displays when changing WiFi settings
- Refactor showRouterNotFoundDialog.
- Modify save order on saving WiFi/Guest WiFi settings

Fixed issues on incredible wifi

---

lib/core/cloud/providers/geolocation/geolocation_provider.dart
lib/core/cloud/providers/geolocation/geolocation_state.dart
lib/core/utils/icon_rules.dart
lib/page/advanced_settings/local_network_settings/providers/local_network_settings_provider.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_server_view.dart
lib/page/advanced_settings/port_forwarding/views/port_range_forwarding_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/single_port_forwarding_rule_view.dart
lib/page/dashboard/views/components/wifi_grid.dart
lib/page/instant_admin/views/manual_firmware_update_view.dart
lib/page/instant_topology/views/instant_topology_view.dart
lib/page/wifi_settings/views/wifi_list_view.dart
lib/page/wifi_settings/views/wifi_term_titles.dart

- Update allow enabling WiFi logic for no LAN ports node.
- Update 5Ghz strings on WiFi list
- Fixed layout error for 2 main WiFi radios
- Remove file data after complete manual fw update
- Add scrollbar on offline node modal
- Add MX57 icon
- Update geolocation display logic

Update wifi enabling logic and geolocation

---

lib/core/jnap/providers/dashboard_manager_provider.dart
lib/core/jnap/providers/dashboard_manager_state.dart
lib/core/jnap/providers/polling_provider.dart
lib/core/jnap/providers/wan_external_provider.dart
lib/core/jnap/providers/wan_external_state.dart
lib/page/instant_verify/providers/instant_verify_provider.dart
lib/page/instant_verify/views/instant_verify_view.dart
lib/route/router_provider.dart

- Extract GetWANExternal as along provider to avoid affecting core transaction.

Fixed polling timeout issue

---

lib/page/nodes/providers/add_nodes_provider.dart

Fix after adding node, didn't show parent node on list.

[Fix] Fix after adding node, didn't show parent node oin list.

---

lib/l10n/app_en.arb
lib/page/components/shortcuts/dialogs.dart
lib/page/components/styled/menus/widgets/top_navigation_menu.dart
lib/page/components/styled/styled_tab_page_view.dart
lib/page/dashboard/views/components/port_and_speed.dart
lib/page/dashboard/views/dashboard_shell.dart
lib/page/instant_safety/views/instant_safety_view.dart
lib/page/instant_setup/data/pnp_provider.dart
lib/page/instant_setup/data/pnp_state.dart
lib/page/instant_setup/model/impl/guest_wifi_step.dart
lib/page/instant_setup/model/impl/personal_wifi_step.dart
lib/page/instant_setup/pnp_admin_view.dart
lib/page/instant_setup/pnp_setup_view.dart
lib/page/instant_setup/troubleshooter/views/pnp_no_internet_connection_view.dart
lib/page/instant_setup/widgets/pnp_stepper.dart
lib/page/instant_setup/widgets/wifi_password_widget.dart
lib/page/instant_setup/widgets/wifi_ssid_widget.dart
lib/page/instant_verify/views/instant_verify_view.dart
lib/page/login/views/local_router_recovery_view.dart
lib/page/wifi_settings/views/wifi_list_view.dart
lib/page/wifi_settings/views/wifi_main_view.dart
lib/validator_rules/rules.dart
test/core/utils/icon_rules_test.dart
test/page/instant_verify/views/localizations/instant_verify_view_test.dart
test/page/wifi_settings/views/localizations/wifi_main_view_test.dart

- Add no internet login flow
- some minor ui fixing
- issue fixing

Add no internet login flow

---

lib/core/utils/logger.dart
lib/main.dart

Add defaultPlatformTarget to the log

Disable semantic label on Android and iOS os

---

lib/core/utils/nodes.dart
lib/page/advanced_settings/dmz/views/dmz_settings_view.dart
lib/page/advanced_settings/firewall/views/ipv6_port_service_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/port_range_forwarding_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/single_port_forwarding_rule_view.dart
lib/page/instant_setup/data/pnp_provider.dart
lib/page/instant_topology/views/instant_topology_view.dart
lib/providers/auth/auth_provider.dart

- Fixed display error on ipv6 port service and port forwarding
- Add new method for check internet connection on Node

Fixed now-198 now-199

---

lib/constants/error_code.dart
lib/l10n/app_en.arb
lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/internet_settings/providers/internet_settings_state.dart
lib/page/advanced_settings/internet_settings/views/connection_type_view.dart
lib/page/advanced_settings/static_routing/static_routing_detail_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_settings_auth_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_pppoe_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_static_ip_view.dart
lib/util/error_code_helper.dart
test/page/advanced_settings/internet_settings/views/localizations/connection_type_view_test.dart
test/page/advanced_settings/internet_settings/views/localizations/internet_settings_mac_clone_view_test.dart

[NOW-194]: [Instant-Setup]: Static IP - DNS2 can't be deleted.

---

lib/core/jnap/models/ipv6_settings.dart
lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/local_network_settings/views/local_network_settings_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_auth_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_save_settings_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_type_selection_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_pppoe_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_static_ip_view.dart
lib/page/instant_setup/troubleshooter/views/pnp_no_internet_connection_view.dart
lib/route/constants.dart
lib/route/route_pnp.dart
lib/route/router_provider.dart

- make ipv6 WANType as optional
- refactor enter ISP connection flow
- update string on local network settings

NOW-201, CHERRY7-23

---

lib/l10n/app_en.arb
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_type_selection_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_pppoe_view.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_static_ip_view.dart
lib/page/wifi_settings/views/wifi_list_view.dart

- Fixed typo
- Add error notice for WiFi Password

[NOW-203][NOW-204]

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_reservations_edit_view.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_reservations_view.dart
lib/page/instant_setup/data/pnp_provider.dart
lib/page/instant_setup/pnp_admin_view.dart

- Revert check internet connection on PnP
- Add MAC and IP check on dhcp reservations
- Fixed error response when set wan type as PPTP or L2TP

Fixed NOW-207

---

lib/route/router_provider.dart

- Try to remove all auth data when entering to PnP

Clean up auth on pnp

---

lib/core/jnap/actions/better_action.dart
lib/core/jnap/actions/jnap_action.dart
lib/core/jnap/actions/jnap_action_value.dart
lib/core/jnap/actions/jnap_service.dart
lib/core/jnap/actions/jnap_service_supported.dart
lib/page/instant_privacy/providers/instant_privacy_provider.dart
pubspec.yaml

- Add macfiltering2 JNAP service
- Add GetSTABSSIDs JNAP action
- Add check sta bssids before enabling instant privacy

add all sta bssids into mac filtering when enabling instant privacy

---

lib/page/advanced_settings/administration/views/administration_settings_view.dart
lib/page/advanced_settings/dmz/views/dmz_settings_view.dart
lib/page/advanced_settings/firewall/views/firewall_view.dart
lib/page/advanced_settings/internet_settings/views/internet_settings_view.dart
lib/page/advanced_settings/local_network_settings/providers/local_network_settings_provider.dart
lib/page/advanced_settings/local_network_settings/providers/local_network_settings_state.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_server_view.dart
lib/page/advanced_settings/local_network_settings/views/local_network_settings_view.dart
lib/page/advanced_settings/static_routing/static_routing_view.dart
lib/route/route_advanced_settings.dart

1. Update UI to the latest version
2. Add more error handling
3. Add unsaved alert on all advanced settings page, excep for Apps and Gaming page

[Rework Local Network]

---

lib/page/components/styled/styled_page_view.dart
lib/page/components/styled/styled_tab_page_view.dart
lib/page/instant_setup/data/pnp_provider.dart
lib/page/instant_setup/model/impl/guest_wifi_step.dart
lib/page/instant_verify/views/components/ping_network_modal.dart
lib/page/instant_verify/views/components/traceroute_modal.dart
lib/page/login/views/local_router_recovery_view.dart

- [NOW-256] Fixed can't go next on PnP Guest settings
- [NOW-255] Fixed UI exceed frame issue
- Add semantics

Issues fixing

---

lib/core/jnap/models/wan_settings.dart
lib/l10n/app_en.arb
lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/internet_settings/views/internet_settings_view.dart
lib/page/advanced_settings/local_network_settings/providers/local_network_settings_provider.dart
lib/page/advanced_settings/local_network_settings/providers/local_network_settings_state.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_server_view.dart
lib/page/advanced_settings/local_network_settings/views/local_network_settings_view.dart

[NOW-274]: Local Network: When changing the host name and adding a DH…CP reservation at the same time, the DHCP reservation is not saved
[NOW-224]: Local Network: It should prompte the user  that the router was not found after changing the DUT IP address
[NOW-278]: Local Network: The local IP address cannot be changed when there is a DHCP reservation
[NOW-275]: Local Network: Deleting DNS/WINS setting should not prompt the user for unsaved changes
[NOW-222]: CLONE - [UI]No show "http://LinksysXXXXX.local" for URL tip when WAN is under Bridge mode.
[NOW-293]: Internet Settings: Unable to edit MAC address field when MAC Address Clone feature is enabled
[InternetSettings] Fix issues on setting vlanId

Fix issues on local network and internet settings

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/internet_settings/views/internet_settings_view.dart
lib/page/dashboard/views/components/internet_status.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_save_settings_view.dart
lib/page/instant_verify/views/instant_verify_view.dart

1. Redirection from bridge to dhcp
2. Fix dashboard ui

Fix issues

---

lib/core/cloud/providers/geolocation/geolocation_provider.dart
lib/core/jnap/models/dyn_dns_settings.dart
lib/core/jnap/router_repository.dart
lib/page/advanced_settings/apps_and_gaming/ddns/providers/ddns_state.dart
lib/page/advanced_settings/apps_and_gaming/ddns/views/dyn_ddns_form.dart
lib/page/advanced_settings/apps_and_gaming/providers/apps_and_gaming_provider.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_reservations_edit_view.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_reservations_view.dart
lib/page/instant_setup/data/pnp_provider.dart
lib/page/instant_setup/pnp_admin_view.dart
lib/page/instant_setup/pnp_setup_view.dart
lib/validator_rules/rules.dart

Add unexcept error handling on pnp config view
Fixed DHCP reservation name rule
Fixed DHCP reservation ip rule
Fixed DDNS data error
Fixed Geolocation null exception error
Fixed scheduleCommand exceedMaxRetry error
Fixed DDNS dyn.com settings error
Fixed guest client devices should not show on reservation list

v1.1.4 minor issues fixing

---

lib/core/jnap/providers/firmware_update_provider.dart
lib/core/jnap/providers/firmware_update_state.dart
lib/page/dashboard/views/dashboard_home_view.dart
lib/page/firmware_update/views/firmware_update_detail_view.dart
lib/page/instant_setup/pnp_setup_view.dart

Fixed: Only one master node status is displayed on the list view after updating the firmware version

[NOW-253] more fix

---

lib/page/instant_setup/troubleshooter/views/pnp_waiting_modem_view.dart

- add spinner when checking internet on the restart modem flow

Fixed NOW-341

---

lib/core/jnap/providers/device_manager_provider.dart
lib/core/jnap/providers/device_manager_state.dart
lib/core/utils/devices.dart
lib/l10n/app_en.arb
lib/page/advanced_settings/local_network_settings/providers/dhcp_reservations_provider.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_reservations_view.dart
lib/page/components/shortcuts/dialogs.dart
lib/page/components/styled/menus/widgets/menu_holder.dart
lib/page/dashboard/views/components/internet_status.dart
lib/page/dashboard/views/components/networks.dart
lib/page/dashboard/views/dashboard_home_view.dart
lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/dashboard/views/prepare_dashboard_view.dart
lib/page/instant_device/providers/device_filtered_list_provider.dart
lib/page/instant_device/providers/device_filtered_list_state.dart
lib/page/instant_device/views/device_detail_view.dart
lib/page/instant_device/views/devices_filter_widget.dart
lib/page/instant_setup/model/impl/guest_wifi_step.dart
lib/page/instant_setup/model/impl/night_mode_step.dart
lib/page/instant_verify/views/instant_verify_view.dart
lib/route/route_menu.dart
lib/route/route_model.dart
lib/route/route_pnp.dart
lib/validator_rules/rules.dart
test/validator_rules/input_validators_test.dart

- NOW-359
- NOW-357
- NOW-349
- NOW-348
- NOW-355
- NOW-360

v1.1.5 issue fixing and enhancement

---

lib/constants/build_config.dart
lib/core/jnap/providers/assign_ip/base_assign_ip.dart
lib/core/jnap/providers/assign_ip/web_assign_ip.dart
lib/core/jnap/router_repository.dart
lib/l10n/app_en.arb
lib/page/advanced_settings/local_network_settings/providers/dhcp_reservations_provider.dart
lib/page/advanced_settings/local_network_settings/providers/local_network_settings_provider.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_reservations_view.dart
lib/page/advanced_settings/local_network_settings/views/local_network_settings_view.dart
lib/page/components/shortcuts/dialogs.dart
lib/page/dashboard/views/components/internet_status.dart
lib/page/dashboard/views/components/port_and_speed.dart
lib/page/instant_setup/data/pnp_provider.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_save_settings_view.dart
lib/route/router_provider.dart

- Fixed dhcp reservations UX issue
- Fixed connection display issue on dashboard
- Fixed error message for pnp isp settings
- Add alert for change local ip address
- Fixed alternative case cause pnp internet check broken
- Fixed UI version not be updated

Fixing now 363 now 360

---

lib/page/instant_topology/providers/instant_topology_provider.dart
lib/page/instant_topology/views/instant_topology_view.dart

https://github.com/user-attachments/assets/0c1b80da-173c-476d-94cc-a904caebdb81

[NOW-239] Remove the child nodes and their children from the topology after factory reset

---

lib/core/jnap/providers/device_manager_provider.dart
lib/page/dashboard/providers/dashboard_home_provider.dart
lib/page/dashboard/providers/dashboard_home_state.dart

- Check detectWANType if no wanType

Update is bridge mode method

---

lib/page/wifi_settings/views/wifi_list_view.dart
lib/validator_rules/input_validators.dart
lib/validator_rules/rules.dart

- Use getRuleByIndex() instead of getRule

Fixed wifi password validator issue

---

lib/route/route_pnp.dart

- Mark all troubleshooting pages as noNaviRail = true

NOW-349: [No Internet] Page with no functional banner after config

---

lib/page/wifi_settings/providers/wifi_advanced_provider.dart
lib/page/wifi_settings/views/wifi_advanced_settings_view.dart
pubspec.yaml

[NOW-227] Update the Wi-Fi advanced setting view layout

---

lib/page/instant_verify/views/instant_verify_view.dart

- Display WAN IP on instant verify page

NOW-372: [Instant-Verify] Instant-Info.: WAN IP displays public IP.

---

lib/app.dart
lib/constants/build_config.dart
lib/constants/url_links.dart
lib/core/cache/linksys_cache_manager.dart
lib/core/jnap/providers/dashboard_manager_provider.dart
lib/core/jnap/providers/polling_provider.dart
lib/page/components/styled/bottom_bar.dart
lib/page/components/styled/menus/widgets/bottom_navigation_menu.dart
lib/page/components/styled/menus/widgets/menu_holder.dart
lib/page/components/styled/menus/widgets/top_navigation_menu.dart
lib/page/components/styled/top_bar.dart
lib/page/dashboard/views/dashboard_home_view.dart
lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/dashboard/views/dashboard_shell.dart
lib/page/dashboard/views/dashboard_support_view.dart
lib/page/instant_admin/views/instant_admin_view.dart
lib/page/support/faq_list_view.dart
lib/route/router_provider.dart
web/index.html

- Remove dependency for PrepareDashboardView.
- Do preparation on RouterProvider
- Optimize menu holder
- Updated term of service's link
- Fixed router password input dialog UI issue on instant admin
- Updated year of copyright

Optimized navigation

---

test/page/advanced_settings/apps_and_gaming/views/localizations/apps_and_gaming_view_test.dart
test/page/advanced_settings/local_network_settings/views/localizations/dhcp_reservations_view_test.dart

Add test case for dhcp reservations page and Apps & Gaming page

[Loc Test] Add test case for dhcp reservations page and Apps & Gaming page

---

lib/constants/url_links.dart
lib/l10n/app_en.arb
lib/page/advanced_settings/local_network_settings/views/dhcp_server_view.dart
lib/page/advanced_settings/local_network_settings/views/local_network_settings_view.dart
lib/page/components/mixin/preserved_state_mixin.dart
lib/page/components/shortcuts/dialogs.dart
lib/page/dashboard/views/components/wifi_grid.dart
lib/page/instant_privacy/providers/instant_privacy_provider.dart
lib/page/instant_privacy/providers/instant_privacy_state.dart
lib/page/instant_privacy/views/instant_privacy_view.dart
lib/page/support/faq_list_view.dart
lib/page/wifi_settings/providers/displayed_mac_filtering_devices_provider.dart
lib/page/wifi_settings/providers/wifi_view_provider.dart
lib/page/wifi_settings/views/mac_filtered_devices_view.dart
lib/page/wifi_settings/views/mac_filtering_view.dart
lib/page/wifi_settings/views/wifi_list_view.dart
lib/page/wifi_settings/views/wifi_main_view.dart
test/mocks/instant_privacy_provider_mocks.dart
test/mocks/wifi_advanced_settings_notifier_mocks.dart
test/page/instant_privacy/views/localizations/instant_privacy_view_test.dart
test/page/wifi_settings/views/localizations/wifi_main_view_test.dart
test/test_data/instant_privacy_test_data.dart
test/test_data/instant_privacy_test_state.dart

- Add MAC filtering view
- Add Warning on instant privacy
- Improve UX on DHCP reservation
- Update url links

MAC filtering and DHCP reservation

---

run_generate_loc_snapshots.sh
test_scripts/combine_results.dart
test_scripts/html_generate_functions.dart
test_scripts/test_result_parser.dart

- improve scrtips
- improve report

Screenshot testing

---

lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/login/views/local_reset_router_password_view.dart

1. Fix issue on instant safety button
2. Add confirm password field on reset password page

Add confirm password field on reset password page and  fix issue on instant safety button

---

lib/page/instant_device/views/select_device_view.dart
lib/page/instant_privacy/providers/instant_privacy_provider.dart
lib/page/support/faq_list_view.dart
lib/page/wifi_settings/views/mac_filtered_devices_view.dart
run_generate_loc_snapshots.sh
test/mocks/instant_privacy_provider_mocks.dart
test/page/advanced_settings/local_network_settings/views/localizations/local_network_settings_view_test.dart
test/page/login/localizations/local_reset_router_password_view_test.dart

- Improve add/delete MACs on MAC filtering page
- Update screenshot testing

Improve MAC filtering and screenshot testing

---

.vscode/launch.json
integration_test/app_test.dart
lib/page/login/views/local_reset_router_password_view.dart
pubspec.yaml

- Add forget password integration test case

Add an integration test case

---

lib/core/jnap/actions/better_action.dart
test/core/jnap/actions/better_action_test.dart

- Implement sorting service function to sort service version
- Add service sorting test cases

NOW-434: GetWanSettings5 not being called

---

lib/core/jnap/providers/ip_getter/get_local_ip.dart
lib/core/jnap/providers/ip_getter/mobile_get_local_ip.dart
lib/core/jnap/providers/ip_getter/web_get_local_ip.dart
lib/l10n/app_en.arb
lib/main.dart
lib/page/dashboard/views/components/wifi_grid.dart
lib/page/wifi_settings/views/wifi_share_detail_view.dart
lib/route/router_provider.dart
lib/util/export_selector/export_base.dart
lib/util/export_selector/export_mobile.dart
lib/util/export_selector/export_web.dart
lib/util/snapshot.dart

- update url strategy to PathUrlStrategy
- Update wifi share icon
- add screenshot widget function
- add save bytes to file function
- add get full location path function

Fixed scanning QR code w/ password not working.

---

lib/page/instant_setup/data/pnp_provider.dart
lib/page/instant_setup/pnp_setup_view.dart

- Fixes wrong steps when WiFi credentials changes on setup flow

NOW-458: PNP setup: Enter the dashboard without doing FW update check and update if the WiFi name/password has changed

---

lib/page/dashboard/views/components/wifi_grid.dart

Fixed the incorrect navigation behavior when states of dashboard wifi toggles change

[WiFi-Toggle]

---

lib/page/instant_setup/data/pnp_provider.dart

Do the set admin password first.

[Pnp] Modify the save function in pnp provider. 

---

lib/app.dart
lib/page/components/layouts/idle_checker.dart
lib/page/components/layouts/root_container.dart

- Add whitelist for idle check
- Add add nodes page into idle check white list to prevent user been logged out when add nodes

NOW-484: Cherry7_Feature request_longer screen timeout

---

lib/page/instant_verify/views/instant_verify_view.dart

- Cleanup WAN status on print format
- Cleanup Backhaul info on print function
- Add Device list on print function

NOW-483: Cleanup WAN status on print function

---

lib/l10n/app_en.arb
lib/page/wifi_settings/providers/wifi_item.dart
lib/page/wifi_settings/views/wifi_list_view.dart

- Add description on WiFi list page
- Rearrange WiFi table layout

NOW-500: Incredible WIFI GUI change

---

lib/l10n/app_en.arb
lib/page/dashboard/views/components/port_and_speed.dart
lib/page/instant_verify/views/components/speed_test_external_widget.dart
lib/page/instant_verify/views/components/speed_test_widget.dart
lib/page/instant_verify/views/instant_verify_view.dart

- Update UI for not supporting health check on dashboard
- Update UI for not supporting health check on instant verify

NOW-499: Speed test GUI change

---

lib/l10n/app_en.arb
lib/page/components/shortcuts/dialogs.dart

- Update string for child node

NOW-482: [String update] Update reboot popup message

---

lib/core/jnap/providers/firmware_update_provider.dart

Fixes incorrect JNAP call when router is supporting nodes firmware update

---

lib/page/instant_topology/views/instant_topology_view.dart
lib/page/instant_topology/views/widgets/tree_node_item.dart

- Add supports smaller layout for mobile screen

NOW-497: Instant Topology showing clipped frame

---

integration_test/actions/base_actions.dart
integration_test/actions/incredible_wifi_actions.dart
integration_test/actions/topbar_actions.dart
integration_test/config/integration_test_config.dart
integration_test/incredible_wifi_name_and_password_test.dart
integration_test/recovery_and_login_test.dart
integration_test/test_meta/incredible_wifi_name_and_password_test.json
lib/page/wifi_settings/views/wifi_list_view.dart

Implement the test for wifi name and password

[Integration Test] Implement the test for wifi name and password

---

lib/page/instant_device/views/device_detail_view.dart
lib/page/nodes/views/node_detail_view.dart

- Add SelectableArea on both device details and node details page

NOW-504: Device list_Improvement_Allow copy function for troubleshooting purposes in Device list

---

lib/core/jnap/actions/better_action.dart
lib/core/jnap/actions/jnap_action_value.dart
lib/core/jnap/actions/jnap_service.dart

- Add support Router14 service
- Add support SetWANSettings5

NOW-511: Add supports router14 service and SetWANSettings5

---

integration_test/shell_scripts/pre_paired.sh
integration_test/test_meta/dashboard_home_test.json
integration_test/test_meta/factory_reset_setup_test.json
integration_test/test_meta/incredible_wifi_name_and_password_test.json
integration_test/test_meta/instant_admin_test.json
integration_test/test_meta/instant_safety_test.json
integration_test/test_meta/menu_test.json
integration_test/test_meta/prepaired_reset_setup_test.json
integration_test/test_meta/recovery_and_login_test.json
integration_web.sh

Add tags in meta
Add -g parameter to set tags

Add supports tag

---

integration_test/actions/advanced_routing_actions.dart
integration_test/actions/advanced_settings_actions.dart
integration_test/actions/base_actions.dart
integration_test/advanced_routing_test.dart
integration_test/test_meta/advanced_routing_test.json

Added integration testing for Advanced Routing feature in Advanced Settings

[Advanced Routing Test]

---

lib/core/utils/icon_rules.dart
lib/page/dashboard/views/components/wifi_grid.dart
test/core/utils/icon_rules_test.dart
test_scripts/test_result_parser.dart

- Add supports M60, M61, M62 series
- Update test cases for testing icon rules

NOW-519: Change model number SPNM to M series

---

lib/page/dashboard/providers/dashboard_home_provider.dart
lib/page/dashboard/providers/dashboard_home_state.dart
lib/page/dashboard/views/dashboard_menu_view.dart
lib/page/health_check/views/speed_test_view.dart
lib/page/instant_verify/views/components/speed_test_widget.dart
test/page/dashboard/localizations/dashboard_menu_view_test.dart
test/page/health_check/views/localizations/speed_test_external_test.dart
test/page/health_check/views/localizations/speed_test_view_test.dart
test/page/instant_verify/views/localizations/instant_verify_view_test.dart

- Switch to internal speed test tile on menu page if routers support speed test
- Add Ookla logo on Speed test page
- Add Ookla logo on instant verify speed test tile

NOW-537: Check speed test module on menu page

---

lib/l10n/app_en.arb
lib/page/dashboard/views/components/port_and_speed.dart

- Update strings for speed test tile
- Add tap action for open KB article in new tab

NOW-526: Add link to KB article explaining speed test results. add text to speed test section in GUI

---

lib/page/dashboard/views/components/port_and_speed.dart
lib/page/instant_topology/views/widgets/tree_node_item.dart

- Fixs external speed description size scale up issue
- Fixs cross draw twice if slave offline. Remove cross for slave, only for master on topology

Fixs minor issues

---

integration_test/actions/base_actions.dart
integration_test/actions/dhcp_reservation_actions.dart
integration_test/dhcp_reservation_test.dart
integration_test/test_meta/dhcp_reservations_test.json
lib/page/advanced_settings/local_network_settings/views/dhcp_reservations_view.dart

Add integration test for dhcp reservations

[Integration Test] Add integration test for dhcp reservations

---

lib/core/jnap/providers/firmware_update_provider.dart
lib/page/instant_admin/views/manual_firmware_update_view.dart
lib/page/wifi_settings/views/wifi_list_view.dart

- Increase timeout to 300 seconds
- Handle timeout exceptions

NOW-566: [Pinnacle 2.0] Instant-Admin: Manual firmware update shows failed message

---

lib/page/wifi_settings/views/wifi_advanced_settings_view.dart
lib/page/wifi_settings/views/wifi_main_view.dart

- Fixs merge error on WiFi Advanced Page error
- Remove bridge mode check on MAC filtering page

NOW-582: The Advanced page is blank

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/wifi_settings/views/wifi_advanced_settings_view.dart
lib/page/wifi_settings/views/wifi_main_view.dart

- Fixs merge error which didn't update the latest changes

NOW-585: Internet Settings: Unknown error displayed when changing the Internet connection type to bridge mode

---

integration_test/shell_scripts/check_auto_parent.sh
integration_test/shell_scripts/jnap.sh
integration_test/shell_scripts/utils.sh
integration_test/test_meta/administration_test.json
integration_test/test_meta/advanced_routing_test.json
integration_test/test_meta/apps_and_gaming_test.json
integration_test/test_meta/dhcp_reservations_test.json
integration_test/test_meta/dmz_test.json
integration_test/test_meta/firewall_test.json
integration_test/test_meta/incredible_wifi_advanced_and_mac_filtering_test.json
integration_test/test_meta/incredible_wifi_test.json
integration_test/test_meta/instant_admin_test.json
integration_test/test_meta/instant_privacy_test.json
integration_test/test_meta/instant_safety_test.json

[NOW-586]: Integration: [Phase 2] Supports auto master behavior on Pinnacle
- Add check_auto_parent to test setup for all integration tests
- Update password check logic to consider admin password set by user
- Ensure proper handling of auto parent behavior in test setup

[NOW-586]: Integration: [Phase 2] Supports auto master behavior on Pinnacle

---

lib/page/instant_admin/views/timezone_view.dart
lib/page/instant_verify/views/instant_verify_view.dart
test/page/instant_admin/views/localizations/instant_admin_view_test.dart
test/page/instant_setup/localizations/pnp_setup_view_test.dart
test/page/instant_verify/views/localizations/instant_verify_view_test.dart
test/page/login/localizations/local_reset_router_password_view_test.dart

This PR includes fixes for screenshot testing in version 1.2.1.

Fix 1.2.1 screenshot testing

---

lib/page/components/shared_widgets.dart
lib/page/firmware_update/views/firmware_update_detail_view.dart
lib/page/firmware_update/views/firmware_update_table.dart
lib/page/instant_setup/model/impl/your_network_step.dart
lib/page/instant_setup/pnp_admin_view.dart
lib/page/nodes/views/add_nodes_view.dart
lib/page/nodes/views/node_detail_view.dart
lib/page/select_network/views/select_network_view.dart
lib/page/wifi_settings/views/wifi_settings_channel_finder_view.dart

- Add device-xl for higher resolution of device images
- Add mx6200 and ln12 to device-xl

NOW-588: Improve resolutions for router images

---

lib/page/advanced_settings/internet_settings/views/internet_settings_view.dart
lib/validator_rules/rules.dart
test/validator_rules/input_validators_test.dart

- Update IPv6WithReservedRule
- Update IPv4WithReservedRule
- Fixes issue on InternetSettings view

NOW-594, NOW-595: Fixes UI issue

---

integration_test/shell_scripts/utils.sh

- fixes get_current_wifi_ssid not working on Mac OS 15

Not able to get current wifi SSID 

---

lib/main.dart
lib/page/instant_device/views/select_device_view.dart
lib/page/wifi_settings/providers/displayed_mac_filtering_devices_provider.dart
lib/page/wifi_settings/views/mac_filtered_devices_view.dart

- Add connection attribute when navigate to select device page
- Do not identify wired device on mac filtering device view

NOW-433: MAC Filtering: Wired device should not appear in the online devices list

---

lib/page/instant_device/views/instant_device_view.dart
lib/page/nodes/views/node_detail_view.dart

- Modifies UX scrolling behaviors on Mobile layout instant device page and node details page

NOW-630: Instant-Device: Unable to scroll down the device list page on mobile device

---

lib/page/components/styled/styled_page_view.dart
lib/page/dashboard/views/components/internet_status.dart
lib/page/dashboard/views/dashboard_home_view.dart
lib/page/instant_topology/views/instant_topology_view.dart
lib/page/instant_verify/views/instant_verify_view.dart
lib/utils.dart

NOW-624: Refresh feature for topology/dashboard - Add refresh function on dashboard, topology, and instant verify - Update widget library

NOW-624: Refresh feature for topology/dashboard

---

integration_test/actions/administration_actions.dart
integration_test/actions/advanced_settings_actions.dart
integration_test/actions/firewall_actions.dart
integration_test/administration_test.dart
integration_test/advanced_routing_test.dart
integration_test/local_network_settings_test.dart

1. Adjusted UI element locating logic for the Administration feature based on the latest screen layout.
2. Updated the Advanced Routing feature to determine accessibility according to the model number and supported functions.
3. Enhanced the Firewall feature to support the updated IPv6 form and fixed related issues.
4. Fixed the timing issues in the local network settings feature by extending the duration of the pumpFrames method.

[Integration Testing]

---

integration_test/internet_settings_set_3_test.dart
test_scripts/extract_failure_messages.dart

- fixes issues on internet_settings_set_3_test.dart
- remove extract error message

fixes issues on internet_settings_set_3_test.dart
