linksys/PrivacyGUI

lib/core/jnap/extensions/batch_extension.dart
lib/page/administration/network_admin/providers/router_password_provider.dart

Fix the router password hint display incorrect after set a new router password hint.
Force fetch password hint from the router
Tested with OAK on local build

Fix router password hint display incorrect after set a new router password

---

lib/page/devices/views/devices_filter_widget.dart
test/common/test_responsive_widget.dart

- Fixed device filter display white block when node name is too long
- Fixed unexcepted error when given a specific device size but the test case not supported

Fixed device filter display white block when node name is too long

---

lib/page/wifi_settings/providers/guest_wifi_provider.dart
lib/page/wifi_settings/views/guest_wifi_view.dart
lib/page/wifi_settings/views/mac_filtered_devices_view.dart

1. Fix the duplicate mac address in mac filtering
2. Sync the guest wifi state to dashboard

[Wifi Setting] 1. Fix the duplicate mac address in mac filtering 2. Sync the guest wifi state to dashboard

---

lib/page/instant_admin/providers/timezone_provider.dart
lib/page/instant_admin/views/instant_admin_view.dart

[Root cause]
Fetch cache data not the latest.
[Soluiton]
Fetch the latest data after save changes.

[NOW-104]: Instant-Admin: After changing, the time zone still displays the previous setting

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/internet_settings/views/internet_settings_mac_clone_view.dart

[Soluiton]
Handle the error response 'ErrorInvalidMACAddress'. Fix the state error issue after saving.

[NOW-133] MAC Address Clone: Unknown error when saving invalid MAC address

---

lib/page/login/views/local_reset_router_password_view.dart

[Solution]
Always display the tips on the reset password page

[Now-111] Reset password: Password tips collapse once leave password column.

---

lib/constants/error_code.dart
lib/core/jnap/actions/jnap_service_supported.dart
lib/page/login/views/login_local_view.dart
lib/providers/auth/auth_provider.dart

[Root cause]
Did not handle the error response: errorPasswordCheckDelayed
[Solution]
Handle the error errorPasswordCheckDelayed, so that will not show unknown error to user.
Add getAdminPasswordAuthStatus to check the auth status

[NOW-77]: Log in: Unknown error displayed when logging in with wrong password and then refreshing the page and logging in with correct password

---

lib/app.dart
lib/constants/build_config.dart
lib/core/jnap/providers/firmware_update_provider.dart
lib/page/components/customs/rotating_icon.dart
lib/page/components/styled/general_settings_widget/general_settings_widget.dart
lib/page/components/styled/styled_page_view.dart
lib/page/instant_admin/views/manual_firmware_update_view.dart

- fixed restart poll data after router back
- UI update, to hide menu during updating and restarting
- Remove start/stop polling when tab lose focus
- Modify manual fw update flow
- refactor fetch ui version
- fixed manual fw update not align in middle and animations

Fixing manual fw update

---

lib/page/nodes/views/node_detail_view.dart

- NOW-147: [Instant-Topology] "Blink Device Light" should be hidden when the node doesn't support the function.

Fixed NOW-147

---

lib/page/advanced_settings/local_network_settings/providers/local_network_settings_provider.dart
lib/page/advanced_settings/local_network_settings/views/local_network_settings_view.dart

[Root cause]
Did not call the setState funciton when update the latest state.
[Solution]
Update the state in the setState function.

[NOW-159]: Local Network: Clearing DNS server settings should not prompt the user for unsaved changes

---

lib/l10n/app_en.arb
lib/page/instant_safety/views/instant_safety_view.dart

[Root cause]
Didn't update the string
[Solution]
Update the string.

[NOW-160]: Instant-Safety: The feature name should display "Instant-Safety" instead of "Safe Browsing"

---

lib/page/advanced_settings/local_network_settings/providers/local_network_settings_provider.dart

[Root cause]
Didn't update instantSafety state
[Solution]
Update instatntSafety state after set lan setting

[NOW-161]: Menu page: The Instant-Safety status is not updated after changing DNS settings

---

lib/page/advanced_settings/administration/providers/administration_settings_provider.dart
lib/page/advanced_settings/administration/providers/administration_settings_state.dart
lib/page/advanced_settings/administration/views/administration_settings_view.dart
lib/page/dashboard/views/components/wifi_grid.dart
lib/page/instant_safety/views/instant_safety_view.dart
lib/page/wifi_settings/providers/wifi_list_provider.dart
lib/page/wifi_settings/providers/wifi_state.dart
lib/page/wifi_settings/views/wifi_list_view.dart
lib/providers/auth/auth_provider.dart

Fixed checking LAN ports, if no LAN ports then the Main WiFi can not be disabled. The wireless local management option applied the same logic

- NOW-141: [Cherry 7_Corner case] Disable WiFi settings, user can't access WebGUI.

---

lib/page/advanced_settings/dmz/providers/dmz_settings_provider.dart
lib/page/advanced_settings/dmz/views/dmz_settings_view.dart
lib/page/advanced_settings/port_forwarding/views/port_range_forwarding_rule_view.dart
lib/page/advanced_settings/port_forwarding/views/port_range_triggering_rule_view.dart
lib/page/advanced_settings/static_routing/static_routing_detail_view.dart

- [NOW-178] DMZ: Error message displays when selecting destination target from DHCP client table then saving
- [NOW-179] DMZ: Unable to change Source IP Address setting
- [NOW-180] DMZ: Error message displays when changing destination IP address setting
- [NOW-181] Port Range Triggering: Should not display error message if the forwarded range's end port is equal to the start port
- [NOW-183] Port Range Forwarding/Port Range Triggering: Should not display error message when changing port setting

Fixed a part of advanced settings issues

---

lib/page/advanced_settings/apps_and_gaming/providers/apps_and_gaming_provider.dart

- Fixed as a workaround - try save using different order to saving port rules if failed.

[NOW-318] Apps & Gaming: It should not prompt the user that the rule could not be created when the overlapping rule was removed

---

lib/page/instant_admin/providers/timezone_provider.dart
lib/page/instant_admin/views/timezone_view.dart

- Set autoAdjustForDST as false if selected timeZone doesn't support it.
- Show snackbar for set timezone operation

NOW-389: Instant-Admin: Cannot change time zone to a time zone that does not support daylight saving time

---

lib/page/instant_privacy/providers/instant_privacy_device_list_provider.dart

- Hide MACs which can not be found on devices

NOW-298: Instant-Privacy: Child node MAC addresses should not be listed in the devices list when this feature is enabled

---

lib/core/utils/icon_rules.dart
lib/core/utils/nodes.dart
lib/page/wifi_settings/views/mac_filtering_view.dart
test/core/utils/icon_rules_test.dart
test/core/utils/nodes_test.dart

- Add Pinnacle 2.0/2.1/2.2 model
- Add support Pinnacle icon
- Add test cases for icon rules and nodes
- Fixed minor UI issue on MAC filtering

NOW-435: Add Pinnacle device to the linksysNow code base

---

lib/page/advanced_settings/local_network_settings/providers/local_network_settings_provider.dart
lib/page/advanced_settings/local_network_settings/views/dhcp_server_view.dart
lib/page/advanced_settings/local_network_settings/views/local_network_settings_view.dart
lib/route/route_advanced_settings.dart

[Root cause]
The wrong logic causes the state not to update properly.
[Solution]
Remove the preserved state in dhcp server view. Use the function in local network settings view to make sure the logic is consistent.

[NOW-449]: Local Network: After saving DHCP server changes and going to "DHCP Reservations", the user should no longer be prompted to save changes

---

lib/validator_rules/rules.dart

Root cause: The Lookbehind assertion in JS RegExp is not supported by Safari, below the iOS version 16.4
https://caniuse.com/js-regexp-lookbehind
As a result, the RegExp used for the SSID check is revised.

[NOW-477] Fixed the crashed screen on PNP setup pages

---

lib/page/instant_setup/data/pnp_provider.dart

- Put close command to the last order in the transaction

NOW:506- Re-order JNAP commands in PnP save settings transaction

---

lib/page/wifi_settings/views/wifi_term_titles.dart

Fixed the incorrectly displayed titles for channels 64 and 69

[NOW-502] Correct two of the Wi-Fi channel titles

---

lib/page/instant_admin/providers/power_table_provider.dart

NOW-507: Region string [United States] replace to wrong [Australia / New Zealand]

---

lib/page/components/styled/styled_tab_page_view.dart
lib/page/dashboard/views/components/networks.dart
lib/page/dashboard/views/components/port_and_speed.dart
lib/page/dashboard/views/components/wifi_grid.dart
lib/page/instant_device/views/device_detail_view.dart
lib/page/instant_setup/troubleshooter/views/pnp_unplug_modem_view.dart
run_generate_loc_snapshots.sh
test/page/dashboard/localizations/dashboard_home_view_test.dart

- Adjust info tile on the dashboard network card
- Adjust wifi card on the dashboard
- Adjust speed test tile on the dashboard
- Adjust title layout on styled tab page
- Add offline node in node info tile screenshot test case
- Fixes overflowed on pnp unplug modem dialog
- Fixes overflowed on edit device name dialog
- Fixes version didn't pass into screenshot testing properly.

Minor UI fixes

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/advanced_settings/internet_settings/views/internet_settings_view.dart

Disable Release & Renew button when IPv6 set to passthrough. Fix a settings issue on setting ipv6 back to automatic.

[NOW-531][Internet Settings] IPv6 set to passthrough, Release & Renew option should be disabled.

---

lib/core/utils/nodes.dart
lib/page/instant_setup/data/pnp_provider.dart
test/core/utils/nodes_test.dart

- Remove isNode check on checkInternetConnection on PnP provider

NOW-555: Internect connectivity check does not work with new model number

---

lib/page/wifi_settings/views/wifi_advanced_settings_view.dart

- Fetch wifi settings after save wifi advanced settings

NOW-553: WiFi channel didn't change once DFS settings is enabled in WiFi advanced settings

---

lib/page/advanced_settings/advanced_settings_view.dart
lib/page/dashboard/views/components/wifi_grid.dart

1. Added error handler for WiFi toggles on the grid of the dashboard to prevent infinite spinner issues
2. Remove the empty condition check in every build() of the advanced setting view to prevent the issue where languages cannot be switched
https://github.com/user-attachments/assets/d25f6b2c-3d58-4e41-b33f-3d010a1c59c6

[NOW-525][NOW-522]

---

lib/page/advanced_settings/internet_settings/providers/internet_settings_provider.dart
lib/page/instant_admin/views/manual_firmware_update_view.dart

Remove time estimation on FW update page. Use infinite linear progress bar instead.

[NOW-544]: Remove time estimation on FW update page. Use infinite linear progress bar instead.

---

lib/page/dashboard/views/components/wifi_grid.dart

NOW-514: Share WiFi: Should not display QR code when clicking on the specific area

---

lib/page/wifi_settings/providers/wifi_item.dart

- Modified the logic for checking wireless mode to include Be or Mixed mode
- The MLO warning message will no longer display on the "You're updating Wi-Fi settings" dialog if all bands have the same SSID, password, and security type
- Updated wireless mode checking logic in the Wi-Fi settings component
- Added/Modified test cases to verify the fix
- [NOW-616](https://jira.belkin.com/browse/NOW-616)

NOW-616: Fix MLO warning message display in Wi-Fi settings dialog

---

lib/page/instant_setup/widgets/wifi_ssid_widget.dart
lib/page/wifi_settings/views/wifi_list_view.dart

Fixed the issue where the error message is not shown for overly long WiFi SSIDs assigned in
(1) input boxes of several bands on the Incredible WiFi 
(2) input box in the Instant Setup flow

[NOW-611] Fixed the issue where the error message is not shown for overly long WiFi SSIDs

---

lib/core/jnap/actions/better_action.dart
lib/core/jnap/actions/jnap_action.dart
lib/core/jnap/actions/jnap_action_value.dart
lib/l10n/app_en.arb
lib/page/components/customs/stateful_popup_menu_item.dart
lib/page/components/shortcuts/dialogs.dart
lib/page/instant_topology/views/instant_topology_view.dart
lib/page/instant_topology/views/widgets/tree_node_item.dart
lib/page/nodes/providers/add_wired_nodes_provider.dart
lib/page/nodes/providers/add_wired_nodes_state.dart
lib/page/nodes/views/add_wired_nodes_view.dart
lib/route/constants.dart
lib/route/route_add_nodes.dart
lib/route/router_provider.dart

This pull request introduces the ability to initiate both wired and wireless node pairing directly from the topology view.
- The "Instant Pair" action in the node's context menu has been replaced with a submenu containing "Pair wired node" and "Pair wireless node".
- Selecting "Pair wired node" now triggers the auto-onboarding process for wired nodes and displays a progress dialog. The user can cancel this process.
- Selecting "Pair wireless node" navigates to the existing wireless node adding flow.
- Added new translations for the pairing actions and dialogs.
- Introduced a `StatefulPopupMenuItem` to support complex widgets within popup menus.
- Refactored the `add_wired_nodes_provider` to allow for better control and cancellation of the pairing process.

[NOW-149] Add wired and wireless pairing from topology view

---

lib/core/jnap/providers/side_effect_provider.dart
lib/page/instant_setup/troubleshooter/views/isp_settings/pnp_isp_save_settings_view.dart

This branch refactors the side effect provider to be able to catch the latest JNAP result. When saving ISP settings failed, instead of showing a generic error message, it now shows a more specific error message to indicate what went wrong.

[NOW-610] [PPPoE - Error Handling] When entering an invalid value into the PPPoE settings, the expected error handling does not appear.

---

lib/page/instant_privacy/providers/instant_privacy_provider.dart
lib/page/wifi_settings/providers/displayed_mac_filtering_devices_provider.dart
lib/page/wifi_settings/views/mac_filtered_devices_view.dart

This branch addresses an issue where child node MAC addresses were being unintentionally added to the filtered devices list when MAC filtering was enabled.
Changes:
*   `bssids` from `InstantPrivacyState` are now converted to uppercase to ensure consistent MAC address comparison.
*   The `macAddresses` list in `displayed_mac_filtering_devices_provider.dart` is now filtered to exclude `bssids`.
*   The unused import of `instant_privacy_state.dart` has been removed from `mac_filtered_devices_view.dart`.

[NOW-617] CLONE - After enable mac filter child node mac will auto add into filtered devices

---

lib/core/jnap/providers/firmware_update_provider.dart
lib/page/firmware_update/views/firmware_update_detail_view.dart

This is because some node objects that need to be updated are missing from the DeviceManager, and therefore the 'firstWhere' method will throw an error. (This may occur in the Pinnacle routers with CF production.)
Solution: Save the node objects and their corresponding status into memory as a cache, which can be used later if the node objects unexpectedly get lost during rebooting.

[NOW-589] Fixed unexpected blank screen after updating FW versions

---

lib/core/utils/nodes.dart
lib/page/advanced_settings/advanced_settings_view.dart

This change hides the RIP routing settings for specific Velop models.
- Added isHidingRipRouting property to the node configuration for several Velop models in lib/core/utils/nodes.dart.
- Introduced a new utility function, isHidingRipRouting, to determine whether to hide the routing feature based on the devices model and hardware version.
- Updated lib/page/advanced_settings/advanced_settings_view.dart to conditionally display the Advanced Routing section based on the output of the isHidingRipRouting function.

[NOW-629]: Advanced Routing - Static routing can be set but has no function

---

lib/l10n/app_en.arb
lib/page/components/layouts/root_container.dart
lib/page/instant_topology/views/instant_topology_view.dart
lib/page/instant_topology/views/widgets/tree_node_item.dart
lib/page/nodes/providers/add_wired_nodes_provider.dart
lib/providers/idle_checker_pause_provider.dart

This branch improves the wired pairing user experience by:
*   Removing the time period that disables wired onboarding.
*   Maintaining continuous polling to ensure the topology reflects the current status immediately.
*   Updating the UI to show when a wired child node is online.

[NOW-623]: Improve wired pairing UX

---

lib/page/advanced_settings/firewall/views/ipv6_port_service_list_view.dart
lib/page/advanced_settings/firewall/views/ipv6_port_service_rule_view.dart
lib/validator_rules/rules.dart

This pull request addresses the IPv6 input field revisions outlined in NOW-622.
Key changes include:
- Refactored the IPv6 port service rule view to use real-time form field validators, improving user feedback.
- Updated the IPv6 validation regex to correctly handle various abbreviated address formats.
- Integrated the device picker icon directly into the IPv6 form field as a suffix icon for a more intuitive UI.
- Removed unused properties and imports to streamline the code.

[NOW-622]: IPv6 input field revise

---

lib/page/instant_verify/views/instant_verify_view.dart

This PR resolves NOW-640. Changes include:\n- Updated Instant Verify View to hide mesh health status for the master and wired child nodes in the printed device info.\n- Updated widgets plugin.

NOW-640: Instant-Verify: The parent and wired child node should not show the mesh health status in the printed device info

---

lib/page/instant_topology/views/widgets/tree_node_item.dart

- Hide mesh health if the node is wired connection.

NOW-639: Instant-Topology: The wired child node info should not show the mesh health status

---

integration_test/config/integration_test_config.dart
integration_test/instant_admin_test.dart
integration_test/shell_scripts/reset_password.sh
integration_test/test_meta/instant_admin_test.json
integration_test/test_meta/recovery_and_login_test.json

Updated the integration testing of Instant Admin:
Reset the admin password to the original one during the testing rather than in the teardown

[Instant Admin Testing] Updated the test case
